[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.16"
optimizer_runs = 200
verbosity = 3

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
goerli = "https://goerli.infura.io/v3/de1869554500480391d372841dd9566a"
linea = "https://rpc.goerli.linea.build"
optimism = "https://endpoints.omniatech.io/v1/op/goerli/public"
mantle = "https://rpc.testnet.mantle.xyz"

[etherscan]
goerli = { key = "${GOERLI_API_KEY}" }
linea = { key = "${ LINEA_ETHERSCAN_KEY }", url = "https://goerli.lineascan.build/" }
